frontend:
- changed-files:
  - any-glob-to-any-file:
    - css/**/*
    - file_index.json
    - images/**/*
    - index.html
    - js/**/*

testing:
- changed-files:
  - any-glob-to-any-file:
    - .github/**/*.yml
    - tests/**/*

intersphinx:
- changed-files:
  - any-glob-to-any-file:
    - intersphinx/**/*

all-sky data:
- changed-files:
  - any-glob-to-any-file:
    - allsky/**/*

coordinates data:
- changed-files:
  - any-glob-to-any-file:
    - coordinates/**/*

galactic center data:
- changed-files:
  - any-glob-to-any-file:
    - galactic_center/**/*

l1148 data:
- changed-files:
  - any-glob-to-any-file:
    - l1448/**/*

photometry data:
- changed-files:
  - any-glob-to-any-file:
    - photometry/**/*

sites data:
- changed-files:
  - any-glob-to-any-file:
    - coordinates/sites.json

tests data:
- changed-files:
  - any-glob-to-any-file:
    - testing/**/*

timeseries data:
- changed-files:
  - any-glob-to-any-file:
    - timeseries/**/*

tutorials data:
- changed-files:
  - any-glob-to-any-file:
    - tutorials/**/*

visualization data:
- changed-files:
  - any-glob-to-any-file:
    - visualization/**/*

wcsaxes data:
- changed-files:
  - any-glob-to-any-file:
    - wcsaxes/**/*
